name: "ds-internship-control-system"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
#    ports:
#      - 5433:5432
    environment:
      - POSTGRES_DB=ds-internship-control-system
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=ivakin_danya

  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - 8088:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=ivakin_danya@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=secretpass
    depends_on:
      - db

  gitlab-ce:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-ce
    hostname: 'localhost'
    healthcheck:
      test: curl http://localhost:9876/-/health || exit 1
      interval: 1m
      start_period: 4m
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://localhost:9876"
        gitlab_rails['initial_root_password'] = '${GITLAB_INIT_PASSWORD}'
    ports:
      - '9876:9876'
      - '443:443'
      - '22:22'
    volumes:
      - '${HOST_GITLAB_CONFIG_DIR}:${GITLAB_CONFIG_DIR}'
      - '${HOST_GITLAB_LOGS_DIR}:${GITLAB_LOGS_DIR}'
      - '${HOST_GITLAB_DATA_DIR}:${GITLAB_DATA_DIR}'
    shm_size: '256m'
#
#  gitlab-runner:
#    image: gitlab/gitlab-runner:alpine
#    container_name: gitlab-runner
#    volumes:
#      - './data/gitlab/etc/gitlab-runner:/etc/gitlab-runner:z'
#      - '/var/run/docker.sock:/var/run/docker.sock'

  app:
    image: ds-internship-control-system
    container_name: ds-internship-control-system
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8080"
    depends_on:
      db:
        condition: service_started
      gitlab-ce:
        condition: service_healthy
    environment:
      - GITLAB_PASSWORD=${GITLAB_INIT_PASSWORD}
      - GITLAB_URL=${GITLAB_URL}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
